version: '3.8'

services:
  api-gateway-service:
    build:
      context: ./services/api-gateway-service/  # Assumes Dockerfile is in the current directory
    ports:
      - "3000:3000"  # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=development
      - DB_HOST=db  # Service name as hostname
      - DB_PORT=5432
      - DB_USER=postgres_user
      - DB_PASSWORD=postgres_pass
      - DB_NAME=app_db
      - KAFKA_BROKER=kafka:9092  # For later Pub/Sub integration
    depends_on:
      - db
      - kafka
    networks:
      - app-network



networks:
  app-network:
    driver: bridge

volumes:
  db-data: