name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  api-gateway:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/api-gateway-service
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: services/api-gateway-service/package-lock.json
      - run: npm ci
      - run: npm test

  auth-service:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/auth-service
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: services/auth-service/package-lock.json
      - run: npm ci
      - run: npm test

  core-banking:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/core-banking-service
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: services/core-banking-service/package-lock.json
      - run: npm ci
      - run: npm test

  notification:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: services/notification-service
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: services/notification-service/package-lock.json
      - run: npm ci
      - run: npm test
